services:
  user-service:
    build: .
    ports:
      - "8001:8001"
    container_name: codesnap-user-service
    env_file:
      - .env
    command: python -m uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - dev-network
      - default

  postgres:
    image: postgres:15-alpine
    container_name: postgres-user-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codesnap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

networks:
  dev-network:
    external: true
    name: shared-codesnap-network

volumes:
  postgres_data:
